### ISSUE TITLE
MySQL80 Service Dependency is Removed Upon Installing a New Version of Unimus 

### ISSUE THREAD

**Issue by Charisborn** [netcore-jsa/unimus-linux-installer#6]
Every time I install a new version of Unimus I lose the MySQL80 service dependency that I configured for the Unimus service. Could this behavior possibly be changed?

**Comment by tomaskir** [comment]
Hi, would introducing a new switch to the installer to ONLY deploy the latest binary without touching any of the support files (like the service unit file) be an acceptable solution?

Basically, you could run `./install.sh -u -m` (`-u` = existing unattended mode, `-m` = new argument for minimal upgrade) and be sure that nothing other than the binary change was performed.

**Comment by Charisborn** [comment]
Sounds to me like a good possibility! Would be glad to test it out.

**Comment by tomaskir** [comment]
@vik-unimus since we will be working on the installer due to Rocky support, can you also pick this ticket up? All changes needed for this should be in [src/common/functions/functions.sh](https://github.com/netcore-jsa/unimus-linux-installer/blob/5d918466bb0fe0bb78bdc79892d45d0f1557f5b3/src/common/functions/functions.sh).

In `parse_args` we need to add support for `-m`.

Then we need to skip these steps if `-m` is set:
- `package_list_update`
- `install_dependencies`
- `install_java`
- `remove_application_autostart`
- `download_application_support_files`
- `add_application_autostart`

We should also add a new step to check if Unimus is already present if running with `-m`, as this option should not be used during a first-time run (since it skips most of the necessary system setup for Unimus / Core to work). This should be implemented directly in each product's scripts, not in the generic `functions.sh` file.
